# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class K8x < Formula
  desc "Agentic kubectl - AI-powered Kubernetes operations"
  homepage "https://github.com/shankarg87/k8x"
  version "0.0.99"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/shankarg87/k8x/releases/download/v0.0.99/k8x_Darwin_x86_64.tar.gz"
      sha256 "4e0da070b5850c75214909fbd68d10f800ff97ac4d47ce988fa4d29dd3d561be"

      def install
        bin.install "k8x"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/shankarg87/k8x/releases/download/v0.0.99/k8x_Darwin_arm64.tar.gz"
      sha256 "0ecf728138b3d9b97b0c81280cd765bcca9663aa51ca0951ed22d0790be0e07c"

      def install
        bin.install "k8x"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/shankarg87/k8x/releases/download/v0.0.99/k8x_Linux_x86_64.tar.gz"
      sha256 "c08fd820d1d228311c3528f1bba4ac75358e056c411e2479cf2fc0f653223124"
      def install
        bin.install "k8x"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/shankarg87/k8x/releases/download/v0.0.99/k8x_Linux_arm64.tar.gz"
      sha256 "daa748bceea17a3ffd2ed9d7aecb72287dde466273c7fa623704cdc6d7d20056"
      def install
        bin.install "k8x"
      end
    end
  end

  test do
    system "#{bin}/k8x --version"
  end
end
